//
//  CountryProvider.swift
//  
//
//  Created by Turker Nessa on 12/8/23.
//

import Foundation


protocol CountryProvider {
    /// a dictionary of all known countries keyed by each countries alpha2 code
    var allKnownCountries: [String: Country] { get }
    
    /// get a country for a given Locale
    func find(by locale: Locale) -> Country
    
    /// get a country for a given ISO 3166-1 alpha 2 code
    func find(alpha2Code: String) -> Country
    
    /// get a country for a given ISO 3166-1 alpha 3 code
    func find(alpha3Code: String) -> Country
}

class CountryProviderImpl: CountryProvider {
    lazy var allKnownCountries: [String: Country] = {
        return [
            Country.United_States.alpha3Code: .United_States,
            Country.Canada.alpha3Code: .Canada,
            Country.Mexico.alpha3Code: .Mexico,
            Country.Afghanistan.alpha3Code: .Afghanistan,
            Country.Aland_Islands.alpha3Code: .Aland_Islands,
            Country.Albania.alpha3Code: .Albania,
            Country.Algeria.alpha3Code: .Algeria,
            Country.American_Samoa.alpha3Code: .American_Samoa,
            Country.Andorra.alpha3Code: .Andorra,
            Country.Angola.alpha3Code: .Angola,
            Country.Anguilla.alpha3Code: .Anguilla,
            Country.Antarctica.alpha3Code: .Antarctica,
            Country.Antigua_and_Barbuda.alpha3Code: .Antigua_and_Barbuda,
            Country.Argentina.alpha3Code: .Argentina,
            Country.Armenia.alpha3Code: .Armenia,
            Country.Aruba.alpha3Code: .Aruba,
            Country.Australia.alpha3Code: .Australia,
            Country.Austria.alpha3Code: .Austria,
            Country.Azerbaijan.alpha3Code: .Azerbaijan,
            Country.Bahamas.alpha3Code: .Bahamas,
            Country.Bahrain.alpha3Code: .Bahrain,
            Country.Bangladesh.alpha3Code: .Bangladesh,
            Country.Barbados.alpha3Code: .Barbados,
            Country.Belarus.alpha3Code: .Belarus,
            Country.Belgium.alpha3Code: .Belgium,
            Country.Belize.alpha3Code: .Belize,
            Country.Benin.alpha3Code: .Benin,
            Country.Bermuda.alpha3Code: .Bermuda,
            Country.Bhutan.alpha3Code: .Bhutan,
            Country.Bolivia.alpha3Code: .Bolivia,
            Country.Bonaire_Sint_Eustatius_and_Saba.alpha3Code: .Bonaire_Sint_Eustatius_and_Saba,
            Country.Bosnia_and_Herzegovina.alpha3Code: .Bosnia_and_Herzegovina,
            Country.Botswana.alpha3Code: .Botswana,
            Country.Bouvet_Island.alpha3Code: .Bouvet_Island,
            Country.Brazil.alpha3Code: .Brazil,
            Country.British_Indian_Ocean_Territory.alpha3Code: .British_Indian_Ocean_Territory,
            Country.Brunei.alpha3Code: .Brunei,
            Country.Bulgaria.alpha3Code: .Bulgaria,
            Country.Burkina_Faso.alpha3Code: .Burkina_Faso,
            Country.Burundi.alpha3Code: .Burundi,
            Country.Cape_Verde.alpha3Code: .Cape_Verde,
            Country.Cambodia.alpha3Code: .Cambodia,
            Country.Cameroon.alpha3Code: .Cameroon,
            Country.Cayman_Islands.alpha3Code: .Cayman_Islands,
            Country.Central_African_Republic.alpha3Code: .Central_African_Republic,
            Country.Chad.alpha3Code: .Chad,
            Country.Chile.alpha3Code: .Chile,
            Country.China.alpha3Code: .China,
            Country.Christmas_Island.alpha3Code: .Christmas_Island,
            Country.Cocos_Islands.alpha3Code: .Cocos_Islands,
            Country.Colombia.alpha3Code: .Colombia,
            Country.Comoros.alpha3Code: .Comoros,
            Country.Congo_Democratic_Republic.alpha3Code: .Congo_Democratic_Republic,
            Country.Congo.alpha3Code: .Congo,
            Country.Cook_Islands.alpha3Code: .Cook_Islands,
            Country.Costa_Rica.alpha3Code: .Costa_Rica,
            Country.Cote_d_Ivoire.alpha3Code: .Cote_d_Ivoire,
            Country.Croatia.alpha3Code: .Croatia,
            Country.Cuba.alpha3Code: .Cuba,
            Country.Curacao.alpha3Code: .Curacao,
            Country.Cyprus.alpha3Code: .Cyprus,
            Country.Czechia.alpha3Code: .Czechia,
            Country.Denmark.alpha3Code: .Denmark,
            Country.Djibouti.alpha3Code: .Djibouti,
            Country.Dominica.alpha3Code: .Dominica,
            Country.Dominican_Republic.alpha3Code: .Dominican_Republic,
            Country.Ecuador.alpha3Code: .Ecuador,
            Country.Egypt.alpha3Code: .Egypt,
            Country.El_Salvador.alpha3Code: .El_Salvador,
            Country.Equatorial_Guinea.alpha3Code: .Equatorial_Guinea,
            Country.Eritrea.alpha3Code: .Eritrea,
            Country.Estonia.alpha3Code: .Estonia,
            Country.Ethiopia.alpha3Code: .Ethiopia,
            Country.Falkland_Islands.alpha3Code: .Falkland_Islands,
            Country.Faroe_Islands.alpha3Code: .Faroe_Islands,
            Country.Fiji.alpha3Code: .Fiji,
            Country.Finland.alpha3Code: .Finland,
            Country.France.alpha3Code: .France,
            Country.French_Guiana.alpha3Code: .French_Guiana,
            Country.French_Polynesia.alpha3Code: .French_Polynesia,
            Country.French_Southern_Territories.alpha3Code: .French_Southern_Territories,
            Country.Gabon.alpha3Code: .Gabon,
            Country.Gambia.alpha3Code: .Gambia,
            Country.Georgia.alpha3Code: .Georgia,
            Country.Germany.alpha3Code: .Germany,
            Country.Ghana.alpha3Code: .Ghana,
            Country.Gibraltar.alpha3Code: .Gibraltar,
            Country.Greece.alpha3Code: .Greece,
            Country.Greenland.alpha3Code: .Greenland,
            Country.Grenada.alpha3Code: .Grenada,
            Country.Guadeloupe.alpha3Code: .Guadeloupe,
            Country.Guam.alpha3Code: .Guam,
            Country.Guatemala.alpha3Code: .Guatemala,
            Country.Guernsey.alpha3Code: .Guernsey,
            Country.Guinea.alpha3Code: .Guinea,
            Country.Guinea_Bissau.alpha3Code: .Guinea_Bissau,
            Country.Guyana.alpha3Code: .Guyana,
            Country.Haiti.alpha3Code: .Haiti,
            Country.Heard_Island_and_McDonald_Islands.alpha3Code: .Heard_Island_and_McDonald_Islands,
            Country.Vatican.alpha3Code: .Vatican,
            Country.Honduras.alpha3Code: .Honduras,
            Country.Hong_Kong.alpha3Code: .Hong_Kong,
            Country.Hungary.alpha3Code: .Hungary,
            Country.Iceland.alpha3Code: .Iceland,
            Country.India.alpha3Code: .India,
            Country.Indonesia.alpha3Code: .Indonesia,
            Country.Iran.alpha3Code: .Iran,
            Country.Iraq.alpha3Code: .Iraq,
            Country.Ireland.alpha3Code: .Ireland,
            Country.Isle_of_Man.alpha3Code: .Isle_of_Man,
            Country.Israel.alpha3Code: .Israel,
            Country.Italy.alpha3Code: .Italy,
            Country.Jamaica.alpha3Code: .Jamaica,
            Country.Japan.alpha3Code: .Japan,
            Country.Jersey.alpha3Code: .Jersey,
            Country.Jordan.alpha3Code: .Jordan,
            Country.Kazakhstan.alpha3Code: .Kazakhstan,
            Country.Kenya.alpha3Code: .Kenya,
            Country.Kiribati.alpha3Code: .Kiribati,
            Country.Kuwait.alpha3Code: .Kuwait,
            Country.Kyrgyzstan.alpha3Code: .Kyrgyzstan,
            Country.Lao.alpha3Code: .Lao,
            Country.Latvia.alpha3Code: .Latvia,
            Country.Lebanon.alpha3Code: .Lebanon,
            Country.Lesotho.alpha3Code: .Lesotho,
            Country.Liberia.alpha3Code: .Liberia,
            Country.Libya.alpha3Code: .Libya,
            Country.Liechtenstein.alpha3Code: .Liechtenstein,
            Country.Lithuania.alpha3Code: .Lithuania,
            Country.Luxembourg.alpha3Code: .Luxembourg,
            Country.Macao.alpha3Code: .Macao,
            Country.North_Macedonia.alpha3Code: .North_Macedonia,
            Country.Madagascar.alpha3Code: .Madagascar,
            Country.Malawi.alpha3Code: .Malawi,
            Country.Malaysia.alpha3Code: .Malaysia,
            Country.Maldives.alpha3Code: .Maldives,
            Country.Mali.alpha3Code: .Mali,
            Country.Malta.alpha3Code: .Malta,
            Country.Marshall_Islands.alpha3Code: .Marshall_Islands,
            Country.Martinique.alpha3Code: .Martinique,
            Country.Mauritania.alpha3Code: .Mauritania,
            Country.Mauritius.alpha3Code: .Mauritius,
            Country.Mayotte.alpha3Code: .Mayotte,
            Country.Micronesia.alpha3Code: .Micronesia,
            Country.Moldova.alpha3Code: .Moldova,
            Country.Monaco.alpha3Code: .Monaco,
            Country.Mongolia.alpha3Code: .Mongolia,
            Country.Montenegro.alpha3Code: .Montenegro,
            Country.Montserrat.alpha3Code: .Montserrat,
            Country.Morocco.alpha3Code: .Morocco,
            Country.Mozambique.alpha3Code: .Mozambique,
            Country.Myanmar.alpha3Code: .Myanmar,
            Country.Namibia.alpha3Code: .Namibia,
            Country.Nauru.alpha3Code: .Nauru,
            Country.Nepal.alpha3Code: .Nepal,
            Country.Netherlands.alpha3Code: .Netherlands,
            Country.New_Caledonia.alpha3Code: .New_Caledonia,
            Country.New_Zealand.alpha3Code: .New_Zealand,
            Country.Nicaragua.alpha3Code: .Nicaragua,
            Country.Niger.alpha3Code: .Niger,
            Country.Nigeria.alpha3Code: .Nigeria,
            Country.Niue.alpha3Code: .Niue,
            Country.Norfolk_Island.alpha3Code: .Norfolk_Island,
            Country.North_Korea.alpha3Code: .North_Korea,
            Country.Northern_Mariana_Islands.alpha3Code: .Northern_Mariana_Islands,
            Country.Norway.alpha3Code: .Norway,
            Country.Oman.alpha3Code: .Oman,
            Country.Pakistan.alpha3Code: .Pakistan,
            Country.Palau.alpha3Code: .Palau,
            Country.Palestine.alpha3Code: .Palestine,
            Country.Panama.alpha3Code: .Panama,
            Country.Papua_New_Guinea.alpha3Code: .Papua_New_Guinea,
            Country.Paraguay.alpha3Code: .Paraguay,
            Country.Peru.alpha3Code: .Peru,
            Country.Philippines.alpha3Code: .Philippines,
            Country.Pitcairn.alpha3Code: .Pitcairn,
            Country.Poland.alpha3Code: .Poland,
            Country.Portugal.alpha3Code: .Portugal,
            Country.Puerto_Rico.alpha3Code: .Puerto_Rico,
            Country.Qatar.alpha3Code: .Qatar,
            Country.Reunion.alpha3Code: .Reunion,
            Country.Romania.alpha3Code: .Romania,
            Country.Russia.alpha3Code: .Russia,
            Country.Rwanda.alpha3Code: .Rwanda,
            Country.Saint_Barthelemy.alpha3Code: .Saint_Barthelemy,
            Country.Saint_Helena.alpha3Code: .Saint_Helena,
            Country.Saint_Kitts_and_Nevis.alpha3Code: .Saint_Kitts_and_Nevis,
            Country.Saint_Lucia.alpha3Code: .Saint_Lucia,
            Country.Saint_Martin.alpha3Code: .Saint_Martin,
            Country.Saint_Pierre_and_Miquelon.alpha3Code: .Saint_Pierre_and_Miquelon,
            Country.Saint_Vincent_and_the_Grenadines.alpha3Code: .Saint_Vincent_and_the_Grenadines,
            Country.Samoa.alpha3Code: .Samoa,
            Country.San_Marino.alpha3Code: .San_Marino,
            Country.Sao_Tome_and_Principe.alpha3Code: .Sao_Tome_and_Principe,
            Country.Saudi_Arabia.alpha3Code: .Saudi_Arabia,
            Country.Senegal.alpha3Code: .Senegal,
            Country.Serbia.alpha3Code: .Serbia,
            Country.Seychelles.alpha3Code: .Seychelles,
            Country.Sierra_Leone.alpha3Code: .Sierra_Leone,
            Country.Singapore.alpha3Code: .Singapore,
            Country.Sint_Maarten.alpha3Code: .Sint_Maarten,
            Country.Slovakia.alpha3Code: .Slovakia,
            Country.Slovenia.alpha3Code: .Slovenia,
            Country.Solomon_Islands.alpha3Code: .Solomon_Islands,
            Country.Somalia.alpha3Code: .Somalia,
            Country.South_Africa.alpha3Code: .South_Africa,
            Country.South_Georgia_and_Sandwich_Islands.alpha3Code: .South_Georgia_and_Sandwich_Islands,
            Country.South_Korea.alpha3Code: .South_Korea,
            Country.South_Sudan.alpha3Code: .South_Sudan,
            Country.Spain.alpha3Code: .Spain,
            Country.Sri_Lanka.alpha3Code: .Sri_Lanka,
            Country.Sudan.alpha3Code: .Sudan,
            Country.Suriname.alpha3Code: .Suriname,
            Country.Svalbard_and_Jan_Mayen.alpha3Code: .Svalbard_and_Jan_Mayen,
            Country.Swaziland.alpha3Code: .Swaziland,
            Country.Sweden.alpha3Code: .Sweden,
            Country.Switzerland.alpha3Code: .Switzerland,
            Country.Syria.alpha3Code: .Syria,
            Country.Taiwan.alpha3Code: .Taiwan,
            Country.Tajikistan.alpha3Code: .Tajikistan,
            Country.Tanzania.alpha3Code: .Tanzania,
            Country.Thailand.alpha3Code: .Thailand,
            Country.Timor_Leste.alpha3Code: .Timor_Leste,
            Country.Togo.alpha3Code: .Togo,
            Country.Tokelau.alpha3Code: .Tokelau,
            Country.Tonga.alpha3Code: .Tonga,
            Country.Trinidad_and_Tobago.alpha3Code: .Trinidad_and_Tobago,
            Country.Tunisia.alpha3Code: .Tunisia,
            Country.Turkey.alpha3Code: .Turkey,
            Country.Turkmenistan.alpha3Code: .Turkmenistan,
            Country.Turks_and_Caicos_Islands.alpha3Code: .Turks_and_Caicos_Islands,
            Country.Tuvalu.alpha3Code: .Tuvalu,
            Country.United_Kingdom.alpha3Code: .United_Kingdom,
            Country.US_Minor_Outlying_Islands.alpha3Code: .US_Minor_Outlying_Islands,
            Country.Uganda.alpha3Code: .Uganda,
            Country.Ukraine.alpha3Code: .Ukraine,
            Country.United_Arab_Emirates.alpha3Code: .United_Arab_Emirates,
            Country.Uruguay.alpha3Code: .Uruguay,
            Country.Uzbekistan.alpha3Code: .Uzbekistan,
            Country.Vanuatu.alpha3Code: .Vanuatu,
            Country.Venezuela.alpha3Code: .Venezuela,
            Country.Viet_Nam.alpha3Code: .Viet_Nam,
            Country.British_Virgin_Islands.alpha3Code: .British_Virgin_Islands,
            Country.US_Virgin_Islands.alpha3Code: .US_Virgin_Islands,
            Country.Wallis_and_Futuna.alpha3Code: .Wallis_and_Futuna,
            Country.Western_Sahara.alpha3Code: .Western_Sahara,
            Country.Yemen.alpha3Code: .Yemen,
            Country.Zambia.alpha3Code: .Zambia,
            Country.Zimbabwe.alpha3Code: .Zimbabwe
        ]
    }()
    
    /*
    static var staticList: Set<Country> = Set([
            .United_States,
            .Canada,
            .Mexico,
            .Afghanistan,
            .Aland_Islands,
            .Albania,
            .Algeria,
            .American_Samoa,
            .Andorra,
            .Angola,
            .Anguilla,
            .Antarctica,
            .Antigua_and_Barbuda,
            .Argentina,
            .Armenia,
            .Aruba,
            .Australia,
            .Austria,
            .Azerbaijan,
            .Bahamas,
            .Bahrain,
            .Bangladesh,
            .Barbados,
            .Belarus,
            .Belgium,
            .Belize,
            .Benin,
            .Bermuda,
            .Bhutan,
            .Bolivia,
            .Bonaire_Sint_Eustatius_and_Saba,
            .Bosnia_and_Herzegovina,
            .Botswana,
            .Bouvet_Island,
            .Brazil,
            .British_Indian_Ocean_Territory,
            .Brunei,
            .Bulgaria,
            .Burkina_Faso,
            .Burundi,
            .Cape_Verde,
            .Cambodia,
            .Cameroon,
            .Cayman_Islands,
            .Central_African_Republic,
            .Chad,
            .Chile,
            .China,
            .Christmas_Island,
            .Cocos_Islands,
            .Colombia,
            .Comoros,
            .Congo_Democratic_Republic,
            .Congo,
            .Cook_Islands,
            .Costa_Rica,
            .Cote_d_Ivoire,
            .Croatia,
            .Cuba,
            .Curacao,
            .Cyprus,
            .Czechia,
            .Denmark,
            .Djibouti,
            .Dominica,
            .Dominican_Republic,
            .Ecuador,
            .Egypt,
            .El_Salvador,
            .Equatorial_Guinea,
            .Eritrea,
            .Estonia,
            .Ethiopia,
            .Falkland_Islands,
            .Faroe_Islands,
            .Fiji,
            .Finland,
            .France,
            .French_Guiana,
            .French_Polynesia,
            .French_Southern_Territories,
            .Gabon,
            .Gambia,
            .Georgia,
            .Germany,
            .Ghana,
            .Gibraltar,
            .Greece,
            .Greenland,
            .Grenada,
            .Guadeloupe,
            .Guam,
            .Guatemala,
            .Guernsey,
            .Guinea,
            .Guinea_Bissau,
            .Guyana,
            .Haiti,
            .Heard_Island_and_McDonald_Islands,
            .Vatican,
            .Honduras,
            .Hong_Kong,
            .Hungary,
            .Iceland,
            .India,
            .Indonesia,
            .Iran,
            .Iraq,
            .Ireland,
            .Isle_of_Man,
            .Israel,
            .Italy,
            .Jamaica,
            .Japan,
            .Jersey,
            .Jordan,
            .Kazakhstan,
            .Kenya,
            .Kiribati,
            .Kuwait,
            .Kyrgyzstan,
            .Lao,
            .Latvia,
            .Lebanon,
            .Lesotho,
            .Liberia,
            .Libya,
            .Liechtenstein,
            .Lithuania,
            .Luxembourg,
            .Macao,
            .North_Macedonia,
            .Madagascar,
            .Malawi,
            .Malaysia,
            .Maldives,
            .Mali,
            .Malta,
            .Marshall_Islands,
            .Martinique,
            .Mauritania,
            .Mauritius,
            .Mayotte,
            .Micronesia,
            .Moldova,
            .Monaco,
            .Mongolia,
            .Montenegro,
            .Montserrat,
            .Morocco,
            .Mozambique,
            .Myanmar,
            .Namibia,
            .Nauru,
            .Nepal,
            .Netherlands,
            .New_Caledonia,
            .New_Zealand,
            .Nicaragua,
            .Niger,
            .Nigeria,
            .Niue,
            .Norfolk_Island,
            .North_Korea,
            .Northern_Mariana_Islands,
            .Norway,
            .Oman,
            .Pakistan,
            .Palau,
            .Palestine,
            .Panama,
            .Papua_New_Guinea,
            .Paraguay,
            .Peru,
            .Philippines,
            .Pitcairn,
            .Poland,
            .Portugal,
            .Puerto_Rico,
            .Qatar,
            .Reunion,
            .Romania,
            .Russia,
            .Rwanda,
            .Saint_Barthelemy,
            .Saint_Helena,
            .Saint_Kitts_and_Nevis,
            .Saint_Lucia,
            .Saint_Martin,
            .Saint_Pierre_and_Miquelon,
            .Saint_Vincent_and_the_Grenadines,
            .Samoa,
            .San_Marino,
            .Sao_Tome_and_Principe,
            .Saudi_Arabia,
            .Senegal,
            .Serbia,
            .Seychelles,
            .Sierra_Leone,
            .Singapore,
            .Sint_Maarten,
            .Slovakia,
            .Slovenia,
            .Solomon_Islands,
            .Somalia,
            .South_Africa,
            .South_Georgia_and_Sandwich_Islands,
            .South_Korea,
            .South_Sudan,
            .Spain,
            .Sri_Lanka,
            .Sudan,
            .Suriname,
            .Svalbard_and_Jan_Mayen,
            .Swaziland,
            .Sweden,
            .Switzerland,
            .Syria,
            .Taiwan,
            .Tajikistan,
            .Tanzania,
            .Thailand,
            .Timor_Leste,
            .Togo,
            .Tokelau,
            .Tonga,
            .Trinidad_and_Tobago,
            .Tunisia,
            .Turkey,
            .Turkmenistan,
            .Turks_and_Caicos_Islands,
            .Tuvalu,
            .United_Kingdom,
            .US_Minor_Outlying_Islands,
            .Uganda,
            .Ukraine,
            .United_Arab_Emirates,
            .Uruguay,
            .Uzbekistan,
            .Vanuatu,
            .Venezuela,
            .Viet_Nam,
            .British_Virgin_Islands,
            .US_Virgin_Islands,
            .Wallis_and_Futuna,
            .Western_Sahara,
            .Yemen,
            .Zambia,
            .Zimbabwe,
        ])
    */
    
    func find(by locale: Locale) -> Country {
        if let validRegionCode = locale.regionCode?.uppercased() {
            return allKnownCountries[validRegionCode] ?? .Unknown
        } else {
            return .Unknown
        }
    }
    
    func find(alpha3Code: String) -> Country {
        let uppercasedAlpha3Code = alpha3Code.uppercased()
        if let matchingCountry = allKnownCountries[uppercasedAlpha3Code] {
            return matchingCountry
        } else if uppercasedAlpha3Code == Country.Worldwide.alpha3Code {
            return .Worldwide
        } else {
            return .Unknown
        }
    }
    
    func find(alpha2Code: String) -> Country {
        if let matchingCountry = allKnownCountries.first(where: {$1.alpha2Code.uppercased() == alpha2Code.uppercased() }) {
            return matchingCountry.value
        } else if alpha2Code == Country.Worldwide.alpha2Code {
            return .Worldwide
        } else {
            return .Unknown
        }
    }
}
